
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Stair-Rover
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://www.ektimo.si/
#
# 2. URL of this page
url:              http://zsedo.github.io/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           Biliards
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            http://kck.st/12bbLkw
  #
  # URL of a cover photo of your project
  cover_image:    http://i.imgur.com/7OUaYdg.jpg
  #
  # Use a one-liner to describe your project
  description:    Biliards.
#
# 4. Your Twitter handle
twitter_handle:   
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
  Welcome text. <br />
